language: node_js
services: 
  - postgrespsql
before_script:
  - psql -c 'create database palandas;' -U postgres
script:
  - npm test
node_js:
- "stable"
  
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov